[project]
name = "pipeline-financeiro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "polars>=1.22.0",
    "yfinance>=0.2.52",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
